openeats/feed/urls.py
from django.conf.urls import *
from views import RecentRecipesFeed,TopRecipesFeed

urlpatterns = [
    url(r'^recent/$', RecentRecipesFeed()),
    url(r'^top/$', TopRecipesFeed())]

openeats/list/urls.py
from django.conf.urls import url
from openeats.list import views as list_views

urlpatterns = [
    url(r'^grocery/$', list_views.index, name="grocery_list"),
    url(r'^grocery/recipe/(?P<recipe_slug>[-\w]+)/$', list_views.groceryAddRecipe, name='grocery_addrecipe'),
    url(r'^grocery/mail/(?P<gid>\d+)/$', list_views.groceryMail, name='grocery_mail'),
    url(r'^grocery/delete/(?P<id>\d+)/$', list_views.groceryDelete, name='grocery_delete'),
    url(r'^grocery/ajaxdelete/$', list_views.groceryAjaxDelete, name='grocery_Ajaxdelete'),
    url(r'^grocery/aisle/ajaxdelete/$', list_views.groceryAisleAjaxDelete, name="grocery_aisledelete"),
    url(r'^grocery/create/$', list_views.groceryCreate, name="grocery_create"),
    url(r'^grocery/edit/(?P<user>[-\w]+)/(?P<slug>[-\w]+)/$', list_views.groceryCreate, name='grocery_edit'),
    url(r'^grocery/(?P<user>[-\w]+)/(?P<slug>[-\w]+)/$', list_views.groceryShow, name='grocery_show'),
    url(r'^grocery/print/(?P<user>[-\w]+)/(?P<slug>[-\w]+)/$', list_views.groceryShow, {'template_name':'list/grocery_print.html',}, name='grocery_print'),
    url(r'^grocery/share/(?P<user>[-\w]+)/(?P<slug>[-\w]+)/$', list_views.groceryShareList, name='grocery_share'),
    url(r'^grocery/unshare/(?P<user>[-\w]+)/(?P<slug>[-\w]+)/$', list_views.groceryUnShareList, name='grocery_unshare'),
    url(r'^grocery/grocery-ajax/$', list_views.groceryProfile, name="grocery_profile"),
    url(r'^grocery/aisle/$', list_views.groceryAisle, name="grocery_aisle")]

openeats/tags/urls.py
from django.conf.urls import url
from openeats.tags import views as tags_views

urlpatterns = [url(r'^recipe/(?P<tag>[-\w]+)/$', tags_views.recipeTags, name="recipe_tags")]

openeats/urls.py
from django.conf.urls import include,url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

from django.contrib import admin

from recipe import views as recipe_views

from registration.views import RegistrationView
register = RegistrationView.as_view()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^rosetta/', include('rosetta.urls')),
    url(r'^feed/', include('openeats.feed.urls')),
    url(r'^groups/', include('openeats.recipe_groups.urls')),
    url(r'^ingredient/', include('openeats.ingredient.urls')),
    url(r'^list/', include('openeats.list.urls')),
    url(r'^tags/', include('openeats.tags.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^robots.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    
    url(r'^$', recipe_views.index, name="home"),
    url(r'^recipe/', include('openeats.recipe.urls')),
        
    url(r'^oauth/', include('social_django.urls',namespace='social')),
    url(r'^',include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

openeats/ingredient/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

class Ingredient(models.Model):
    title = models.CharField(_('title'), max_length=250)
    quantity = models.CharField(_('quantity'), max_length=10)
    measurement = models.CharField(_('measurement'), max_length=200, blank=True, null=True)
    preparation = models.CharField(_('preparation'), max_length=100, blank=True, null=True)
    recipe_fk = models.ForeignKey('recipe.Recipe', verbose_name=_('recipe'), related_name='ingredients_fk')
 
    class Meta:
        ordering = ['title']

    def __unicode__(self):
        return self.title

openeats/recipe/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

class Recipe(models.Model):
    title = models.CharField(_("Recipe Title"), max_length=250, default="Add a title here.")
    ingredients = models.TextField(_('ingredients'), default='Add ingredients here.')
    instructions = models.TextField(_('instructions'), default='Add instructions here.')
    description = models.TextField(_('description'), default='Add a description here.')
    user_id = models.IntegerField(_('user_id'),default=0)
    image_location = models.ImageField('image', default='')
    thumbnail_location = models.ImageField('thumbnail', default='')
    
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['title']

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return "/recipe/%s/" % str(self.id)
    

openeats/recipe/forms.py
from django.forms import CharField,ModelForm
from models import Recipe

class RecipeForm(ModelForm):
    description = CharField(required=False)
    class Meta:
        model = Recipe
        fields = ['title','ingredients','instructions','description']
        

openeats/feed/views.py
from django.contrib.syndication.views import Feed
from django.conf import settings
from django.utils.translation import ugettext as _
from openeats.recipe.models import Recipe


class RecentRecipesFeed(Feed):
    title = settings.OETITLE + _(" Recent Recipes")
    link = "/recipe/recent/"
    description = _("Updates added on new recipes added to ") + settings.OETITLE

    def items(self):
        return Recipe.objects.filter(shared=Recipe.SHARE_SHARED).order_by('-pub_date', 'title')[:10]

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.info


class TopRecipesFeed(Feed):
    title = settings.OETITLE + _(" Top Recipes")
    link = "/recipe/top/"
    description =_("Top recipes on ") + settings.OETITLE

    def items(self):
        rating_qs = Recipe.objects.extra(select={'rate': '((100/%s*rating_score/(rating_votes+%s))+100)/2' % (Recipe.rating.range, Recipe.rating.weight)})
        return rating_qs.filter(shared=Recipe.SHARE_SHARED).order_by('-rate')[:10]

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.info

openeats/ingredient/views.py
from django.http import HttpResponse
from models import Ingredient

import json

def autocomplete_ing(request):
    """Used to auto complete ingredient names on the recipe form. This view is called by a jquery script
       returns json list of ten ingredients found
    """
    
    q = request.GET.get('term', '')
    ing_list = Ingredient.objects.filter(title__istartswith=q).values_list('title').distinct().order_by('title')[:10]
    results = []
    for ing_item in ing_list:
        results.append(" ".join(ing_item))
    return HttpResponse(json.dumps(results), mimetype="application/json")

openeats/list/views.py
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.forms.models import inlineformset_factory
from django.utils.translation import ugettext as _
from openeats.recipe.models import Recipe
from models import GroceryList, GroceryItem, GroceryShared, GroceryAisle, GroceryRecipe
from forms import GroceryListForm, GroceryItemFormSet, GroceryUserList, GrocerySendMail, GroceryShareTo, GroceryAisleForm
from datetime import date


@login_required
def index(request):
    """returns a list of grocery list for a user"""
    glist = GroceryList.objects.filter(author=request.user).order_by('-pub_date')
    gshared = GroceryShared.objects.filter(shared_to=request.user).order_by('-list__pub_date')
    return render_to_response('list/grocery_index.html', {'glists': glist, 'gshared': gshared}, context_instance=RequestContext(request))


@login_required
def groceryDelete(request, id):
    """ takes the id of a list andremoves a users grocery list"""
    list = get_object_or_404(GroceryList, author=request.user, id=id)
    list.delete()
    output = _('Your grocery list has been removed.')
    messages.success(request, output)
    return HttpResponseRedirect(reverse('list.views.index'))


@login_required
def groceryAjaxDelete(request):
    if request.method == 'POST':
        if request.POST['id']:
            try:
                list = get_object_or_404(GroceryList, author=request.user, id=request.POST['id'])
            except GroceryList.DoesNotExist:
                raise Http404
            list.delete()
            return redirect("/list/grocery/grocery-ajax/")


@login_required
def groceryCreate(request, user=None, slug=None):
    """used to create and edit grocery list"""
    if user:
        owner = User.objects.get(username=user)  # setting the owner of the list instead of using request.user because if a list is shared request.user won't be the owner
    else:
        owner = request.user  # must be coming in to create a new list and not edit another one this is the only way user wouldn't be passed
        
    ItemFormSet = inlineformset_factory(GroceryList, GroceryItem, extra=15, formset=GroceryItemFormSet, can_delete=True)
    if user and slug:  # must be editing a list that is already created
        cur_list = get_object_or_404(GroceryList, author=owner, slug=slug)

        if owner.id != request.user.id:  # if the person is the the owner check if the list is shared to the user
            shared = GroceryShared.objects.filter(list=cur_list)  # check to see if this list is shared
            if shared:
                if shared[0].shared_to_id != request.user.id:
                    output = _('You do not have permissions to edit this list ')
                    messages.error(request, output)
                    return redirect('grocery_list')
            else:
                output = _('You do not have permissions to edit this list ')
                messages.error(request, output)
                return redirect('grocery_list')

    else:
        cur_list = GroceryList()

    if request.method == 'POST':
      
        form = GroceryListForm(request.POST, instance=cur_list)
        formset = ItemFormSet(request.POST, instance=cur_list, user=owner)
        if form.is_valid() and formset.is_valid():
            new_list = form.save()
            instances = formset.save(commit=False)  # save the items separately
            for instance in instances:
                instance.list_id = new_list.id  # set the grocery id foreign key to the this grocery id
                instance.save()
           
            return redirect('grocery_show', user=new_list.author, slug=new_list.slug)
    else:
        form = GroceryListForm(instance=cur_list)
        formset = ItemFormSet(instance=cur_list, user=owner)

    return render_to_response('list/grocerylist_form.html', {'form': form, 'formset': formset, 'user': owner}, context_instance=RequestContext(request))


@login_required
def groceryShow(request, slug, user, template_name='list/grocery_detail.html'):
    """get the users grocery list and show it to them"""
    owner = User.objects.get(username=user)
    list = get_object_or_404(GroceryList, slug=slug, author=owner)
    if owner.id != request.user.id:  # if the person is the the owner check if the list is shared to the user
        shared = GroceryShared.objects.filter(list=list)  # check to see if this list is shared
        if shared:
            if shared[0].shared_to_id != request.user.id:
                output = _('You do not have permissions to view this list ')
                messages.error(request, output)
                return redirect('grocery_list')
        else:
            output = _('You do not have permissions to view this list ')
            messages.error(request, output)
            return redirect('grocery_list')
        
    return render_to_response(template_name, {'list': list}, context_instance=RequestContext(request))


@login_required
def groceryProfile(request):
    """Returns a list of a users grocery list to be displayed on the users profile"""
    list = GroceryList.objects.filter(author=request.user)
    return render_to_response('list/grocery_ajax.html', {'lists': list}, context_instance=RequestContext(request))


@login_required
def groceryAddRecipe(request, recipe_slug):
    """Takes a recipe and adds all the ingredients from that recipe to a grocery list"""
    if request.method == 'POST':
        # not validating the form since the form is only a prepopulated drop box and can't really be validated
        if request.POST['lists'] == '0':  # must of selected to create a new list because no id can be set to zero otherwise
            list = GroceryList()
            list.title = date.today()
            list.author = request.user
            list.save()
        else:
            list = get_object_or_404(GroceryList, pk=request.POST['lists'], author=request.user)
        recipe = get_object_or_404(Recipe, pk=request.POST['recipe_id'])

        new_groceryRecipe = GroceryRecipe()  # save the recipe added to the grocery list
        new_groceryRecipe.recipe_id = recipe.id
        new_groceryRecipe.list_id = list.id
        new_groceryRecipe.save()

        for ing in recipe.ingredients.all():
            new_item = GroceryItem()
            new_item.list_id = list.id
            new_item.item = str(ing.quantity) + ' ' + str(ing.measurement) + ' ' + ing.title
            new_item.save()

        if recipe.related:
            new_groceryRecipe = GroceryRecipe()
            new_groceryRecipe.recipe_id = recipe.related.id
            new_groceryRecipe.list_id = list.id
            new_groceryRecipe.save()
            for ing in recipe.related.ingredients.all():
                new_item = GroceryItem()
                new_item.list_id = list.id
                new_item.item = str(ing.quantity) + ' ' + str(ing.measurement) + ' ' + ing.title
                new_item.save()

        return redirect('grocery_edit', user=list.author, slug=list.slug)
    else:
        recipe = get_object_or_404(Recipe, slug=recipe_slug)
        form = GroceryUserList(user=request.user)
  
        return render_to_response('list/grocery_addrecipe.html', {'form': form, 'recipe': recipe}, context_instance=RequestContext(request))


@login_required
def groceryShareList(request, user, slug):
    list = get_object_or_404(GroceryList, slug=slug, author=request.user)
    if request.method == 'POST':
        shared_list = GroceryShared(list=list)
        form = GroceryShareTo(request.POST, instance=shared_list)
        if form.is_valid():
            form.save()
            output = _('Your grocery list has been shared.')
            messages.success(request, output)
            return redirect('grocery_show', user=request.user, slug=slug)
    else:
        form = GroceryShareTo()
        form.fields['shared_to'].queryset = request.user.relationships.followers()  # only allow people who are following a user to be allowed to have list shared to them
    return render_to_response('list/grocery_share.html', {'form': form, 'list': list}, context_instance=RequestContext(request))


@login_required
def groceryUnShareList(request, user, slug):
    list = GroceryList.objects.get(slug=slug)
    shared_list = get_object_or_404(GroceryShared, list=list)
    if shared_list.shared_to == request.user or shared_list.shared_by == request.user:
        shared_list.delete()
        output = _("Grocery List has been un-shared")
        messages.success(request, output)
    return redirect('grocery_list')


def groceryMail(request, gid):
    """this view creates a form used to send a grocery list to someone via email"""
    if request.method == 'POST':
        form = GrocerySendMail(data=request.POST, request=request)  # passing the request object so that in the form I can get the request post dict to save the form
        if form.is_valid():
            form.save(fail_silently=False)
            return HttpResponse("grocery list mail sent to " + request.POST['to_email'])
    else:
        form = GrocerySendMail(request=request)
    return render_to_response('list/grocery_email.html', {'form': form, 'gid': gid}, context_instance=RequestContext(request))


@login_required
def groceryAisle(request):
    """used by users to manage their grocery aisles """
    aisles = GroceryAisle.objects.filter(author=request.user)
    grocery_aisle = GroceryAisle()
    grocery_aisle.author = request.user
    if request.method == "POST":
        form = GroceryAisleForm(request.POST, instance=grocery_aisle)

        if form.is_valid():
            form.save()
            output = _("New Aisle added")

openeats/tags/views.py
from taggit.models import Tag, TaggedItem
from django.template import RequestContext
from django.shortcuts import render_to_response, get_object_or_404


def recipeTags(request, tag):
    """displays a list of recipes with a giving tag"""
    recipe_tag = get_object_or_404(Tag, slug=tag)
    recipes_tagged = TaggedItem.objects.filter(tag=recipe_tag)
    recipe_list = []
    for recipe in recipes_tagged:
        recipe_list.append(recipe.content_object)

    return render_to_response('tags/recipe_tags.html', {'recipe_list': recipe_list}, context_instance=RequestContext(request))

openeats/templates/recipe/_list.html
{% comment %}This template is called by other templates to display a list of recipes, the template is passed a recipe object from a list of recipe objects{% endcomment %}

{% load i18n %}
{% load sanitize %}
{% load imagekit %}

{% block jscript %}
  <script type="text/javascript">
    $(document).ready(function () {
      $(".{{ recipe.slug }}-rate").stars({
       inputType:"select", disabled:true
      });
      var avg = '{{recipe.rating.score}}' / '{{recipe.rating.votes}}';
      var selectid = avg - 1;  // the average rating and minus one selects start with zero so a score of one is actuall an id of 0
      $(".{{ recipe.slug }}-rate").stars("selectID", selectid); //set the select value to the avg rate
    });
  </script>
{% endblock %}

<div class="row">
    <div class="col-lg-9">
        <div class="thumbnail well well-sm">
            <a href="{{ recipe.get_absolute_url }}">
            {% if recipe.photo %}
                {% generateimage 'recipe:list' source=recipe.photo -- alt=recipe.photo.name class="pull-right" %}
            {% else %}
                <img class="pull-right" src="{{ STATIC_URL }}images/parsley.jpg" alt="{{ recipe }} photo"/>
            {% endif %}
            </a>
            <div class="caption">
                <h3><a href="{{ recipe.get_absolute_url }}">{{ recipe }}</a></h3>

                <p class="chef">{% trans 'Chef:' %} <a
                        href="{{ recipe.author.get_profile.get_absolute_url }}">{{ recipe.author }}</a></p>

                <form>
                    <div class="{{ recipe.slug }}-rate recipe-rate">
                        <p class="rating-title"><strong>{% trans 'Average Rating:' %}</strong> <span
                                class="rating-cap"></span></p>
                        <select name="selrate">
                            <option value="1">{% trans 'Poor' %}</option>
                            <option value="2">{% trans 'Fair' %}</option>
                            <option value="3">{% trans 'OK' %}</option>
                            <option value="4">{% trans 'Good' %}</option>
                            <option value="5">{% trans 'Wow' %}</option>
                        </select>
                    </div>
                </form>
            </div>
            <div class="recipe-info">
                <p>{{ recipe.info|striptags|truncatewords:'100' }}</p>
            </div>
        </div>
    </div>
</div>

openeats/templates/recipe/index.html
{% extends 'base.html' %} 
{% load i18n %} 
{% load imagekit %} 
{% load static %} 
{% block content %}
<div class="projectList">
	<h3 class="title">Recipes</h3> 
	{% for recipe in recipes %}
	<div class="media">
		<a class="pull-left" href="{{ recipe.get_absolute_url }}">
				  	{% if recipe.thumbnail_location %}
					<img src="{{ recipe.thumbnail_location.url }}" class="projectImg" title="{{ recipe.title }}">
				    {% else %}
					<img src="{% static 'images/eaten_raisin_toast_150_90.jpg' %}" class="projectImg" title="{{ recipe.title }}">
				  	{% endif %}
				  </a>
		<div class="media-body">
			<h4 class="media-heading"><a href="{{ recipe.get_absolute_url }}">{{ recipe.title }}</a></h4>
			<p>
				{{ recipe.description }}
			</p>
			<a class="pull-right" href="{{ recipe.get_absolute_url }}">more details</a>
		</div>
	</div>
	{% endfor %}
</div>
{% endblock %}

openeats/templates/recipe/recipe_cook.html
{% comment %}This template is for the cook view for a recipe{% endcomment %}
{% load i18n %}
{% load sanitize %}


{% if recipe.shared == 1 and recipe.author != request.user %}
  <h2>{%trans 'Recipe is marked Private and you are not the author of it!' %}</h2>
{% else %}

  <div id="tenfoot">
    <div class="page-header">
      <h1>{{ recipe.title }}</h1>
    </div>
    <h2>{% trans 'Ingredients' %}</h2>
      <ul>
        {% for ing in recipe.ingredients.all %}
          <li> {{ ing.quantity }} {{ ing.measurement}} - {{ ing.title }} {{ ing.preparation }}</li>
        {% endfor %}
      </ul>

      {% if recipe.related %}
        <h4>{{ recipe.related }}</h4>
        <ul>
          {% for ing in recipe.related.ingredients.all %}
            <li> {{ ing.quantity }} {{ ing.measurement}} - {{ ing.title }} {{ ing.preparation }}</li>
          {% endfor %}
        </ul>
     {% endif %}

     <div>
       <h2>{%trans 'Directions' %}</h2>
       {{ recipe.directions|sanitize_html|safe }}
       {% if recipe.related %}
         <h4>{{ recipe.related }}</h4>
           {{ recipe.related.directions|sanitize_html|safe }}
       {% endif %}
      </div>
  </div>
{% endif %}

openeats/templates/recipe/recipe_detail.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{%block title %}{{ block.super }}- {{ recipe.title }} {% endblock %}

{% block menu %}

{% endblock %}
{% block content %}
<div id="image_modal" class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Recipe Image Upload</h4>
            </div>
                <div class="modal-body">
                    <label for="image_upload">Image</label>
                    <input type="file" id="image_upload" />
                </div>
                <div class="modal-footer">
                    <button id="image_upload_submit" class="btn btn-primary" value="Submit">
                        <span class="glyphicon glyphicon-ok"></span>
                    </button>
                    <button class="btn btn-default" data-dismiss="modal">
                        <span class="glyphicon glyphicon-remove"></span>
                    </button>
                </div>
        </div>
    </div>
</div>
<div class="row">
<h3 class="title">
    <a href="#" id="title" data-pk="{{ recipe.id }}" 
       data-params="{csrfmiddlewaretoken:'{{ csrf_token }}'}"
       data-url="{% url 'recipe_edit' %}" data-type="text">{{ recipe.title }}</a>
</h3>
</div>
<div class="row">
<div class="media">
    <a href="#" data-target="#image_modal" data-toggle="modal">
    {% if recipe.image_location %}
    <img src="{{ recipe.image_location.url }}" class="pull-left" title="{{ recipe.title }}">
    {% else %}
    <img src="{% static 'images/eaten_raisin_toast_500_300.jpg' %}" class="pull-left" title="{{ recipe.title }}">
    {% endif %}
    </a>
    <div>
        <h4 class="media-heading">Description</h4>
        <a href="#" id="description" data-pk="{{ recipe.id }}"
           data-params="{csrfmiddlewaretoken:'{{ csrf_token }}'}"
           data-url="{% url 'recipe_edit' %}" data-type="textarea">{{ recipe.description }}</a>
    </div>
</div>
</div>
<div class="row">
<div class="col-md-6">
    <h4>Ingredients</h4>
    <a href="#" id="ingredients" data-pk="{{ recipe.id }}"
       data-params="{csrfmiddlewaretoken:'{{ csrf_token }}'}"
       data-url="{% url 'recipe_edit' %}" data-type="textarea">{{ recipe.ingredients }}</a>
</div>
<div class="col-md-6">
    <h4>Instructions</h4>
    <p>
        <a href="#" id="instructions" data-pk="{{ recipe.id }}"
           data-params="{csrfmiddlewaretoken:'{{ csrf_token }}'}"
           data-url="{% url 'recipe_edit' %}" data-type="textarea">{{ recipe.instructions }}</a>
    </p>
</div>
</div>
<div class="row"><br/></div>
<div class="row">
<div class="col-md-6">
    <p>
        Click a recipe section to edit it
        <span class="fa fa-pencil-square-o"></span>.
    </p>
</div>
</div>
{% endblock %}

openeats/templates/recipe/recipe_email.html
{%  load i18n %}
<div>
    <form action="{% url 'recipe_mail' id=id %}" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" name="id" value="{{ id }}" />
        <input type="submit"  />

    </form>
</div>

openeats/templates/recipe/recipe_form.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %} {{ block.super }} - {% trans "Add or edit a recipe" %} {% endblock %}

{% block content %}
<form id="recipe-form" method="post">
    {% csrf_token %}
    <p>
        <label for="id_title">Recipe Title:</label>
        <input id="id_title" maxlength="250" name="title" type="text" value="{{ form.title.value|default_if_none:'' }}" required />
    <p>
        <label for="id_ingredients">Ingredients:</label> 
        <textarea cols="40" id="id_ingredients" name="ingredients" rows="5" required>{{ form.ingredients.value }}</textarea>
    </p>
    <p>
        <label for="id_instructions">Instructions:</label>
        <textarea cols="40" id="id_instructions" name="instructions" rows="5" required>{{ form.instructions.value }}</textarea>
    </p>
    <p>
        <label for="id_description">Description:</label>
        <textarea cols="40" id="id_description" name="description" rows="5">{{ form.description.value|default_if_none:'' }}</textarea>
    </p>        
   <div class="form-actions">
      <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
   </div>
</form>
{% endblock %}

openeats/templates/recipe/recipe_list.html
{% extends "base.html" %}
{% load i18n %}
{% load sanitize %}
{% block feeds %}<link href="{{ feed }}" rel="alternate" type="application/rss+xml" title="{% blocktrans %}{{ title }} Recipe Feed{% endblocktrans %}" />{% endblock %}


{% block content %}
  <div id="title">
      <h3>{% blocktrans %}{{ title }}{% endblocktrans %}</h3>
  </div>
    {% for recipe in recipe_list %}
      {% include '/recipe/_list.html' %}
  {% endfor %}
{% endblock %}

openeats/templates/recipe/recipe_mail_body.html
{% comment %}This template is the template for the recipe email body{% endcomment %}
{% load i18n %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" media="print" href="http://{{ request.get_host }}{{STATIC_URL}}css/grocery_print.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="http://{{ request.get_host }}{{STATIC_URL}}css/grocery_prints.css" />
        <title>{{ OETITLE }}{% trans 'Email'%} {{ list }}</title>
    </head>
    <body>
        <div id="grocery-print">
            <img src="http://{{ request.get_host }}{{ OELOGO }}" alt="OpenEats logo" />
            <p>{{ request.user }}{%  trans ' has shared a recipe with you' %}</p>
            <h2><a href="http://{{ request.get_host }}{{ recipe.get_absolute_url }}">{{ recipe }}</a></h2>
            <div id="photo">
                {% if recipe.photo %}
                   <a id="recipe-photo" href="http://{{ request.get_host }}{{recipe.display.url }}"> <img src="http://{{ request.get_host }}{{ recipe.photo }}" alt="{{ recipe }} photo" /></a>
                {% else %}
                   <a id="recipe-photo" href="http://{{ request.get_host }}{{ STATIC_URL  }}images/parsley.jpg"> <img src="http://{{ request.get_host }}{{ STATIC_URL  }}images/parsley.jpg" alt="{{ recipe }} photo" /></a>
                {% endif %}
            </div>
                {{ recipe.info|safe }}

        </div>
    </body>
</html>

openeats/templates/recipe/user_recipes.html
{% extends 'base.html' %}

{% block content %}
<h2>Your Recipes</h2>
<ul>
{% for recipe in recipe_list %}
    <li><a href="/recipe/{{ recipe.id }}">{{ recipe.title }}</a></li>
{% endfor %}
</ul>
{% endblock %}